### ISSUE TITLE
this script can't live with log.io-server

### ISSUE THREAD

**Issue by vuuihc** [kerphi/log.io-server-parser#1]
As log.io-server and this script both need to listen on port 28777,they can't run at the same time,can they?
Is it designed to run without log.io-server?

**Comment by kerphi** [comment]
log.io-server-parser has been designed to listen on a custom port, but you are right by default it's 28777 port.

To change the port, have a look to the usage example, especially: 

``` javascript
var server = new LogIoServerParser({
  port: 28777
});
```

A common use case is to build a proxy between log.io-harvester and log.io-server.

**Comment by vuuihc** [comment]
Thanks for your reply.Your reply and the testcase t2.js help me understood it. I will use it to help me save the logs received.Do you think it is feasible?

**Comment by kerphi** [comment]
Yes it is :)
